---
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: registry.cigna.com/enterprise-devops/conduit-jnlp:latest
    resources:
      requests: 
        cpu: 150m
        memory: 1000Mi
      limits: 
        cpu: 650m
        memory: 1000Mi
  - name: cloudkit
    image: registry.cigna.com/enterprise-devops/aws-d-cloudkit:plz-2-python-3.11
    command:
    - cat
    workingDir: /home/jenkins/agent
    imagePullPolicy: IfNotPresent
    tty: true
    resources:
      requests: 
        cpu: 150m
        memory: 1000Mi
      limits: 
        cpu: 650m
        memory: 1000Mi
  - name: python-312-ubi9
    image: registry.cigna.com/hpp/python:latest 
    command:
    - cat
    workingDir: /home/jenkins/agent
    imagePullPolicy: IfNotPresent
    tty: true
    resources:
      requests: 
        cpu: 500m
        memory: 1000Mi
      limits: 
        cpu: 650m
        memory: 1500Mi
