"""Static chart catalog data (no imports). Synced from jw_chart_metadata."""

from __future__ import annotations

# (chart_id, designation, view, chart_type, chart_name)
CHART_CATALOG: tuple[tuple[str, str, str, str, str], ...] = (
    ("1", "ccd", "volume", "doughnut", "Provider Group Volume"),
    ("2", "ccd", "volume", "doughnut", "Provider Volume"),
    ("3", "ccd", "spend", "doughnut", "Gross Episode Spend"),
    ("4", "ccd", "spend", "doughnut", "Gross Episode Counts"),
    ("5", "ccd", "spend", "doughnut", "Medical Category Spend"),
    ("6", "ccd", "spend", "doughnut", "Pharmacy Category Spend"),
    ("7", "ccd", "spend", "doughnut", "High-Cost Drugs Spend"),
    ("8", "ccd", "spend", "doughnut", "Per Episode Spend"),
    ("9", "ccd", "utilization", "doughnut", "Member Visits"),
    ("10", "ccd", "utilization", "doughnut", "Client Visits"),
    ("11", "ccd", "utilization", "doughnut", "Claim Count"),
    ("12", "ccd", "utilization", "doughnut", "Claim Procedure Count"),
    ("13", "ccd", "savings", "doughnut", "Gross Savings"),
    ("14", "ccd", "savings", "doughnut", "Episode Savings"),
    ("15", "ccd", "quality", "doughnut", "Groups Meeting Board Cert. Criteria"),
    ("16", "ccd", "quality", "doughnut", "Providers having Board Certification"),
    ("17", "ccd", "quality", "doughnut", "Groups Meeting External Quality Certification Criteria"),
    ("18", "ccd", "quality", "doughnut", "Providers having External Quality Certification"),
    ("19", "ccd", "quality", "doughnut", "Groups Meeting EBM Criteria"),
    ("20", "ccd", "quality", "doughnut", "Providers having EBM Opportunities"),
    ("21", "ccd", "turnover-disruption", "doughnut", "Provider Turnover"),
    ("22", "ccd", "turnover-disruption", "doughnut", "Member-to-Provider Relationships"),
    ("101", "tier-1", "volume", "doughnut", "Provider Group Volume"),
    ("102", "tier-1", "volume", "doughnut", "Provider Volume"),
    ("103", "tier-1", "spend", "doughnut", "Gross Episode Spend"),
    ("104", "tier-1", "spend", "doughnut", "Gross Episode Counts"),
    ("105", "tier-1", "spend", "doughnut", "Medical Category Spend"),
    ("106", "tier-1", "spend", "doughnut", "Pharmacy Category Spend"),
    ("107", "tier-1", "spend", "doughnut", "High-Cost Drugs Spend"),
    ("108", "tier-1", "spend", "doughnut", "Per Episode Spend"),
    ("109", "tier-1", "utilization", "doughnut", "Member Visits"),
    ("110", "tier-1", "utilization", "doughnut", "Client Visits"),
    ("111", "tier-1", "utilization", "doughnut", "Claim Count"),
    ("112", "tier-1", "utilization", "doughnut", "Claim Procedure Count"),
    ("113", "tier-1", "savings", "doughnut", "Gross Savings"),
    ("114", "tier-1", "savings", "doughnut", "Episode Savings"),
    ("115", "tier-1", "quality", "doughnut", "Groups Meeting Board Cert. Criteria"),
    ("116", "tier-1", "quality", "doughnut", "Providers having Board Certification"),
    ("117", "tier-1", "quality", "doughnut", "Groups Meeting External Quality Certification Criteria"),
    ("118", "tier-1", "quality", "doughnut", "Providers having External Quality Certification"),
    ("119", "tier-1", "quality", "doughnut", "Groups Meeting EBM Criteria"),
    ("120", "tier-1", "quality", "doughnut", "Providers having EBM Opportunities"),
    ("121", "tier-1", "turnover-disruption", "doughnut", "Provider Turnover"),
    ("122", "tier-1", "turnover-disruption", "doughnut", "Member-to-Provider Relationships"),
)
